export const metrics = {
  acceleration: {
    x: {},
    y: {},
    z: {}
  },
  awareness: {
    creativity: {},
    comprehension: {},
    attention: {},
    meditation: {}
  },
  brainwaves: {
    raw: {},
    frequency: {},
    powerByBand: {},
    psd: {}
  },
  channelAnalysis: {
    FC1: {},
    FC2: {},
    FC3: {},
    FC4: {},
    CP1: {},
    CP2: {},
    CP3: {},
    CP4: {}
  },
  emotion: {
    joy: {},
    sadness: {},
    anger: {},
    surprise: {},
    excitement: {},
    disappointment: {},
    fear: {},
    love: {},
    stress: {},
    interest: {}
  },
  facialExpression: {
    smile: {},
    laugh: {},
    frown: {},
    blink: {},
    winkLeft: {},
    winkRight: {}
  },
  kinesis: {
    rest: {},
    artifactDetector: {},
    leftArm: {},
    rightArm: {},
    leftHandPinch: {},
    rightHandPinch: {},
    tongue: {},
    jumpingJacks: {},
    leftFoot: {},
    rightFoot: {},
    leftThumbFinger: {},
    leftIndexFinger: {},
    leftMiddleFinger: {},
    leftRingFinger: {},
    leftPinkyFinger: {},
    rightThumbFinger: {},
    rightIndexFinger: {},
    rightMiddleFinger: {},
    rightRingFinger: {},
    rightPinkyFinger: {},
    mentalMath: {},
    bitingALemon: {},
    push: {},
    pull: {},
    lift: {},
    drop: {},
    moveLeft: {},
    moveRight: {},
    moveForward: {},
    moveBackward: {},
    rotateLeft: {},
    rotateRight: {},
    rotateClockwise: {},
    rotateCounterClockwise: {},
    disappear: {}
  },
  predictions: {
    rest: {},
    artifactDetector: {},
    leftArm: {},
    rightArm: {},
    leftHandPinch: {},
    rightHandPinch: {},
    tongue: {},
    jumpingJacks: {},
    leftFoot: {},
    rightFoot: {},
    leftThumbFinger: {},
    leftIndexFinger: {},
    leftMiddleFinger: {},
    leftRingFinger: {},
    leftPinkyFinger: {},
    rightThumbFinger: {},
    rightIndexFinger: {},
    rightMiddleFinger: {},
    rightRingFinger: {},
    rightPinkyFinger: {},
    mentalMath: {},
    bitingALemon: {},
    push: {},
    pull: {},
    lift: {},
    drop: {},
    moveLeft: {},
    moveRight: {},
    moveForward: {},
    moveBackward: {},
    rotateLeft: {},
    rotateRight: {},
    rotateClockwise: {},
    rotateCounterClockwise: {},
    disappear: {}
  },
  status: {
    battery: {},
    charging: {},
    connected: {},
    powered: {},
    updating: {}
  }
};

export default {
  metrics
};
